# Generated by Django 4.1.4 on 2023-01-09 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FatLossJourneyParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('initial_cut_date', models.DateTimeField()),
                ('cal_deficit_per_day', models.IntegerField()),
                ('days_journey_length', models.IntegerField()),
                ('weight_initial_dry', models.FloatField()),
                ('bf_initial', models.FloatField()),
                ('delta_bf_initial', models.FloatField()),
                ('deficit_days_per_week', models.IntegerField()),
                ('daily_deficit_uncertainty', models.IntegerField(default=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
