# Generated by Django 4.1.5 on 2023-01-21 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0002_fatlossjourneyparams_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightBF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField()),
                ('weight', models.FloatField()),
                ('bf_percent', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
