# Generated by Django 4.1.5 on 2023-01-22 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_whycut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightbf',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
